Repository ArkEcosystem/laravel-ui, pull requests merged in 2021-02, with the labels that each got.

#294 refactor: accordion component toggling tweaks
  resources/lang/en/actions.php
  resources/views/accordion.blade.php
Labels: Complexity: Low, Type: Refactor

#295 fix: use cloak for toggle title
  resources/views/accordion.blade.php
Labels: Complexity: Low, Type: Bugfix

#296 fix: cloak the correct accordion title
  resources/views/accordion.blade.php
Labels: Complexity: Low, Type: Bugfix

#297 refactor: update textarea label include
  resources/views/inputs/textarea.blade.php
Labels: Complexity: Low, Type: Refactor

#301 chore: add shield icon
  resources/assets/icons/shield.svg
Labels: Complexity: Low, Type: Task

#298 refactor: textarea maxlength property
  resources/views/inputs/textarea.blade.php
Labels: Complexity: Low, Type: Refactor

#303 refactor: switch ordered/unordered list icons in WYSIWYG editor
  icons.html
  resources/views/inputs/markdown.blade.php
Labels: Complexity: Low, Type: Refactor

#300 feat: markdown parser for fields edited with the basic wyswyg editor
  resources/assets/js/markdown-editor/css/style.css
  resources/views/inputs/markdown.blade.php
  src/Support/MarkdownParser.php
Labels: Complexity: Low, Type: Feature

#304 refactor: update secondary button style
  resources/assets/css/_buttons.css
Labels: Complexity: Low, Type: Refactor

#307 refactor: add disable tile link style
  resources/assets/css/_components.css
Labels: Complexity: Low, Type: Refactor

#306 feat: advertise and document write icons
  icons.html
  resources/assets/icons/advertise.svg
  resources/assets/icons/document-write.svg
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#308 fix: advertise icon viewbox
  resources/assets/icons/advertise.svg
Labels: Complexity: Low, Type: Bugfix

#302 refactor: make `details-box` component alignment configurable
  resources/views/details-box.blade.php
Labels: Complexity: Low, Type: Task

#310 fix: tippy whitelist deep purge
  icons.html
  resources/tailwind.config.js
Labels: Complexity: Low, Type: Bugfix

#311 feat: rule for validating the length of the text resulted from a markdown text
  resources/lang/en/validation.php
  src/Rules/MarkdownMaxChars.php
  tests/Rules/MarkdownMaxCharsTest.php
Labels: Complexity: Medium, Type: Feature

#305 feat: add full-screen property to dropdown component
  EXAMPLES.md
  README.md
  resources/views/dropdown.blade.php
Labels: Complexity: Low, Type: Feature

#313 chore: update pr template checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Low, Type: Task

#314 fix: tag input error tooltip
  .github/PULL_REQUEST_TEMPLATE.md
  resources/assets/js/tags.js
  resources/views/inputs/includes/input-error-tooltip.blade.php
  resources/views/inputs/tags.blade.php
Labels: Complexity: Low, Type: Bugfix
