Repository ArkEcosystem/laravel-ui, pull requests merged in 2021-03, with the labels that each got.

#312 refactor: alert component tweaks and update icons
  icons.html
  resources/assets/css/_alerts.css
  resources/assets/icons/alert-danger.svg
  resources/assets/icons/alert-default.svg
  resources/assets/icons/alert-error.svg
  resources/assets/icons/alert-hint.svg
  resources/assets/icons/alert-info.svg
  resources/assets/icons/alert-success.svg
  resources/assets/icons/alert-warning.svg
  resources/assets/icons/checkmark-smooth.svg
  resources/assets/icons/checkmark-thin.svg
  resources/assets/icons/cross.svg
  resources/assets/icons/exclamation-mark.svg
  resources/assets/icons/exclamation.svg
  resources/assets/icons/info.svg
  resources/assets/icons/question-mark.svg
  resources/views/alert.blade.php
  resources/views/status-circle-shallow.blade.php
  src/Components/FlashMessage.php
  src/helpers.php
Labels: Complexity: Medium, Type: Feature

#317 chore: update pr template checklist with screenshot item
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Low, Type: Task

#319 refactor: tweak alerts to match new design
  resources/assets/css/_alerts.css
  resources/views/alert.blade.php
Labels: Complexity: Low, Type: Refactor

#299 refactor: allow limit for selection tiles
  resources/assets/css/_components.css
  resources/views/inputs/includes/tile-selection-option.blade.php
  resources/views/inputs/tags.blade.php
  resources/views/inputs/tile-selection.blade.php
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#321 fix: fix issue when minifying `_expandable.css`
  resources/assets/css/_expandable.css
Labels: Complexity: Low, Type: Bugfix

#320 refactor: added showMore slot for the expandable component
  resources/views/expandable.blade.php
Labels: Complexity: Low, Type: Refactor

#322 feat: initialize tooltips when a livewire component is updated
  resources/assets/js/tippy.js
Labels: Complexity: Low

#324 chore: improve expandable component
  EXAMPLES.md
  README.md
  resources/views/expandable.blade.php
Labels: Complexity: Low, Type: Task

#325 feat: add button-tag css class
  resources/assets/css/_buttons.css
Labels: Complexity: Low, Type: Feature

#323 refactor: disabled tags input style tweaks
  resources/assets/css/_forms.css
  resources/views/inputs/tags.blade.php
Labels: Complexity: Low, Type: Refactor

#326 fix: disabled tile tooltip
  resources/views/inputs/includes/tile-selection-option.blade.php
Labels: Complexity: Medium, Type: Bugfix

#327 refactor: tooltip on the tags component if disabled
  resources/views/inputs/tags.blade.php
Labels: Complexity: Low, Type: Refactor

#330 fix: js-modal fixed position to prevent autoscrolling
  resources/views/js-modal.blade.php
Labels: Complexity: Low, Type: Task

#329 fix: reset error bag after displaying upload error
  src/Components/Concerns/HandleUploadError.php
  src/Components/UploadImageCollection.php
  src/Components/UploadImageSingle.php
Labels: Complexity: Low, Type: Bugfix

#331 fix: add tile styling height to tailwind config
  resources/tailwind.config.js
Labels: Complexity: Low, Type: Bugfix

#332 refactor: slider component
  resources/assets/css/_slider.css
  resources/views/includes/slider/header.blade.php
  resources/views/includes/slider/navigation.blade.php
  resources/views/includes/slider/scripts.blade.php
  resources/views/slider.blade.php
Labels: Complexity: High, Type: Refactor

#335 fix: make wire:key of the delete button unique
  resources/views/inputs/upload-image-collection.blade.php
  resources/views/inputs/upload-image-single.blade.php
Labels: Complexity: Low, Type: Bugfix

#339 fix: reduce border radius on notification dropdown
  resources/views/navbar/notifications.blade.php
Labels: Complexity: Low, Type: Bugfix

#338 fix: disabled tile tooltip
  resources/views/inputs/includes/tile-selection-option.blade.php
Labels: Complexity: Low, Type: Bugfix

#333 refactor: keep pointer events on disabled tiles
  resources/assets/css/_components.css
Labels: Complexity: Low, Type: Task

#334 fix: dont init alpine by default on the inputs
  resources/assets/js/tags.js
  resources/views/inputs/includes/input-error-tooltip.blade.php
  resources/views/inputs/includes/input-field.blade.php
  resources/views/inputs/input-with-prefix.blade.php
  resources/views/inputs/input.blade.php
  resources/views/inputs/tags.blade.php
Labels: Complexity: Low, Type: Bugfix

#340 fix: rollback html entities when editing
  src/Casts/Markdown.php
Labels: Complexity: Low, Type: Bugfix

#342 fix: rich select is using the name variable incorrectly
  resources/views/inputs/rich-select.blade.php
Labels: Complexity: Low, Type: Bugfix

#341 refactor: external url component props
  resources/views/external-link.blade.php
Labels: Complexity: Low, Type: Refactor

#344 feat: allow to upload multiple files at time on upload images component
  resources/views/inputs/upload-image-collection.blade.php
  src/Components/Concerns/HandleUploadError.php
  src/Components/UploadImageCollection.php
Labels: Complexity: Low, Type: Feature

#328 feat: user tagging input component
  EXAMPLES.md
  README.md
  resources/assets/css/_user_tagger.css
  resources/assets/js/markdown-editor/css/style.css
  resources/assets/js/user-tagger.js
  resources/views/inputs/user-tagger.blade.php
  src/UserInterfaceServiceProvider.php
Labels: Complexity: Medium, Type: Feature

#345 refactor: modal padding tweak
  resources/assets/css/_components.css
  resources/views/modal.blade.php
Labels: Complexity: Low, Type: Refactor

#347 fix: dont allow more images than the limit / make the limit overridable
  resources/views/inputs/upload-image-collection.blade.php
  src/Components/UploadImageCollection.php
Labels: Type: Bugfix

#348 chore: resolution friendly chevron down icon
  resources/assets/icons/chevron-down.svg
Labels: Complexity: Low, Type: Task

#350 chore: remove console.log
  icons.html
  resources/assets/js/user-tagger.js
Labels: Complexity: Low, Type: Task

#349 chore: resolution friendly chevron up
  icons.html
  resources/assets/icons/chevron-up.svg
Labels: Complexity: Low, Type: Task

#351 chore: useful resources icons
  icons.html
  resources/assets/icons/enter.svg
  resources/assets/icons/plus-square.svg
  resources/assets/icons/what-is-next.svg
Labels: Complexity: Medium, Type: Task

#352 feat: event listener to remove temporary tag from input
  resources/assets/js/tags.js
Labels: Complexity: Low, Type: Refactor

#346 chore: improve components for e2e tests
  resources/lang/en/general.php
  resources/views/dropdown.blade.php
  resources/views/navbar.blade.php
  resources/views/navbar/logo.blade.php
  resources/views/navbar/profile.blade.php
Labels: Complexity: Low, Status: Needs Review, Type: Task

#353 fix: set the initial value of the user tagger
  resources/assets/js/user-tagger.js
Labels: Complexity: Low, Type: Bugfix

#356 refactor: slider bottom padding
  resources/assets/css/_slider.css
Labels: Complexity: Low, Type: Refactor

#357 fix: revert slider bottom padding
  resources/assets/css/_slider.css
Labels: Complexity: Low

#360 refactor: allow to tag user through name or display name
  resources/assets/js/user-tagger.js
Labels: Complexity: Low, Type: Refactor

#358 feat: use responsive images for navbar profile photos
  resources/views/dropdown.blade.php
  resources/views/expandable.blade.php
  resources/views/navbar/profile.blade.php
  resources/views/slider-slide.blade.php
  tests/Mocks/MediaMock.php
  tests/Views/NavbarTest.php
  tests/Views/Navigation/Dropdown/ProfileTest.php
Labels: Complexity: Low, Type: Feature

#359 feat: responsive markdown design
  resources/assets/js/markdown-editor/css/style.css
  resources/assets/js/markdown-editor/markdown-editor.js
  resources/assets/js/markdown-editor/plugins/alert.js
  resources/assets/js/markdown-editor/plugins/preview.js
  resources/assets/js/markdown-editor/plugins/reference.js
  resources/assets/js/markdown-editor/plugins/underline.js
Labels: Complexity: Medium, Type: Feature

#362 refactor: twitter id wording
  resources/assets/js/markdown-editor/plugins/twitter.js
Labels: Complexity: Low, Type: Refactor

#361 fix: update js-modal to match livewire modal design
  resources/views/js-modal.blade.php
Labels: Complexity: Low, Type: Task

#364 fix: remove vertical space on mobile for tile selection component
  resources/views/inputs/includes/tile-selection-option.blade.php
Labels: Complexity: Low, Type: Bugfix

#366 refactor: metatags trim image
  resources/views/metatags.blade.php
Labels: Complexity: Low, Type: Refactor

#367 fix: metatags trailing slash
  resources/views/metatags.blade.php
Labels: Complexity: Low, Type: Bugfix

#370 fix: disable tile selection while making requests
  resources/views/inputs/includes/tile-selection-option.blade.php
Labels: Complexity: Low, Type: Bugfix

#369 fix: prevent the notification dropdown to be larger than screens
  resources/views/secondary-menu.blade.php
Labels: Complexity: Low, Type: Task

#371 refactor: input field tweaks
  resources/assets/css/_forms.css
  resources/views/inputs/includes/input-field.blade.php
Labels: Complexity: Low, Type: Refactor

#372 refactor: responsive text css helper
  resources/assets/css/_general.css
Labels: Complexity: Low, Type: Refactor

#373 revert: "fix: disable tile selection while making requests"
  resources/views/inputs/includes/tile-selection-option.blade.php
Labels: Complexity: Low, Type: Bugfix

#376 fix: use mb_strlen to correctly count unicode chars
  src/Rules/MarkdownMaxChars.php
  tests/Rules/MarkdownMaxCharsTest.php
Labels: Complexity: Low, Type: Bugfix

#375 fix: broken mobile hidden behaviour on tiles
  resources/views/inputs/includes/tile-selection-option.blade.php
Labels: Complexity: Low, Type: Bugfix

#374 fix: remove selection tiles select all and use only wire:model
  resources/views/inputs/includes/tile-selection-option.blade.php
  resources/views/inputs/tile-selection.blade.php
Labels: Complexity: Low, Type: Feature

#377 feat: add minimum dimensions to image upload
  src/Components/UploadImageCollection.php
  src/Components/UploadImageSingle.php
Labels: Complexity: Low, Type: Feature

#365 refactor: update wysiwyg editor button styling and change import
  README.md
  resources/assets/css/_markdown-editor.css
  resources/assets/js/markdown-editor/markdown-editor.js
Labels: Complexity: Low, Status: Needs Review

#379 fix: tags disabled tooltip
  resources/views/inputs/tags.blade.php
Labels: Complexity: Low, Type: Bugfix

#380 refactor: make the markdown scripts a separate file to import
  README.md
  resources/assets/js/markdown-editor/markdown-editor.js
  resources/views/pages/includes/markdown-scripts.blade.php
Labels: Complexity: Medium, Type: Refactor

#381 chore: update readme with correct markdown editor copy command
  README.md
Labels: Complexity: Low, Type: Task

#382 chore: adjust markdown editor setup steps
  README.md
Labels: Complexity: Low, Type: Task

#384 perf: add font loader component
  EXAMPLES.md
  README.md
  resources/assets/css/_fonts.css
  resources/views/font-loader.blade.php
  src/UserInterfaceServiceProvider.php
  tests/Helpers.php
  tests/Views/FontLoaderTest.php
Labels: Complexity: Medium, Type: Performance

#383 fix: break works on user tagger to prevent horizontal growing
  resources/views/inputs/user-tagger.blade.php
Labels: Complexity: Low, Type: Task

#385 refactor: update profile dropdown margin
  resources/views/dropdown.blade.php
  resources/views/navbar/profile.blade.php
Labels: Complexity: Low, Type: Refactor

#386 refactor: tags case insensitive
  resources/assets/js/tags.js
Labels: Complexity: Low, Type: Refactor

#368 refactor: improve dusk discoverability and accessibility
  resources/views/inputs/includes/tile-selection-option.blade.php
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#391 feat: add input field `autocapitalize` attribute
  resources/views/inputs/includes/input-field.blade.php
  tests/Views/Inputs/InputTest.php
Labels: Complexity: Low, Type: Feature

#378 refactor: focus state
  resources/assets/css/_forms.css
  resources/views/accordion.blade.php
  resources/views/dropdown.blade.php
  resources/views/inputs/input-with-icon.blade.php
  resources/views/inputs/upload-image-single.blade.php
  resources/views/navbar/logo.blade.php
  resources/views/navbar/notifications.blade.php
  resources/views/navbar/profile.blade.php
  resources/views/social-link.blade.php
  tests/Views/Inputs/InputWithIconTest.php
Labels: Complexity: Low, Status: Needs Review

#393 refactor: alert component
  resources/assets/css/_alerts.css
  resources/views/alert.blade.php
Labels: Complexity: Low, Type: Refactor

#363 feat: upload the wysiwyg images to a public url
  README.md
  config/ui.php
  resources/assets/js/markdown-editor/markdown-editor.js
  resources/assets/js/markdown-editor/utils/utils.js
  src/Http/Controllers/WysiwygControlller.php
  src/UserInterfaceServiceProvider.php
Labels: Complexity: Medium, Type: Feature

#387 feat: add slots to contact page and footer for custom social media
  icons.html
  resources/assets/icons/brands/3speak.svg
  resources/assets/icons/brands/bitchute.svg
  resources/assets/icons/brands/lbry.svg
  resources/assets/icons/brands/outline/mail.svg
  resources/views/footer-social.blade.php
  resources/views/pages/contact/content.blade.php
Labels: Complexity: Medium, Type: Feature

#394 fix: remove double border on custom profile picture
  resources/lang/en/general.php
  resources/views/navbar/profile.blade.php
Labels: Complexity: Low, Type: Bugfix

#397 fix: add viewbox to mail icon
  icons.html
  resources/assets/icons/brands/outline/mail.svg
Labels: Complexity: Low, Type: Bugfix

#398 refactor: check image onload is set
  resources/views/dropdown.blade.php
  resources/views/expandable.blade.php
Labels: Complexity: Low, Type: Refactor

#400 refactor: add contact page props for content
  resources/views/pages/contact/content.blade.php
Labels: Complexity: Low, Type: Refactor

#401 refactor: default no results text
  resources/lang/en/general.php
  resources/views/no-results.blade.php
Labels: Complexity: Low, Type: Refactor

#402 refactor: tooltip option for dropdown component
  EXAMPLES.md
  resources/views/dropdown.blade.php
Labels: Complexity: Low, Type: Refactor

#404 fix: trim markdown text before counting
  src/Rules/MarkdownMaxChars.php
  tests/Rules/MarkdownMaxCharsTest.php
Labels: Complexity: Low, Type: Bugfix

#403 fix: add unique wire:key error tooltip to prevent overlapping
  resources/views/inputs/includes/input-error-tooltip.blade.php
Labels: Complexity: Low, Type: Bugfix

#405 feat: add option for modals with a fixed position
  resources/views/modal.blade.php
Labels: Complexity: Low, Type: Feature
